### ISSUE TITLE
exoplanet data processing error?

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#10]
A number of errors with plot-exo using 066a49460a.

I think there is something wrong with the exoplanets data processing.

The opening plot page discovery year - plmass is empty. and if I try and change the x or y parameters I get 
```
builtins.ValueError
ValueError: min() arg is an empty sequence
```
with the last line of the traceback being
```
File "/home/jneal/Phd/Codes/SWEETer-Cat/sweetercat/app.py", line 202, in plot_exo
x1 = min(x)
```
So x is empty here.
If I try add a colorbar to the blank plot I get 
```
builtins.ValueError
ValueError: Bin edges must be unique: array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg
```
Which occurs when reaching this line
```
File "/home/jneal/Phd/Codes/SWEETer-Cat/sweetercat/app.py", line 243, in plot_exo
groups = pd.qcut(z.values, len(COLORS))
```

**Comment by DanielAndreasen** [comment]
Oh wait, did you try to install `PyAstronomy` first? I forgot to add that to the `requirements.txt`

**Comment by jason-neal** [comment]
Yes, version 0.11.0. The app wouldn't run without it installed.

**Comment by DanielAndreasen** [comment]
Do you use python3? This might be the problem here. I'll try to make a new enviroment.

**Comment by jason-neal** [comment]
Yes usually, but I tried it on 2.7 also.

**Comment by DanielAndreasen** [comment]
I can reproduce this with python 3.6

**Comment by DanielAndreasen** [comment]
Okay, the problem is when merging the two data frames together in [L51](https://github.com/DanielAndreasen/SWEETer-Cat/blob/master/sweetercat/app.py#L51). The names doesn't match. A quick fix for Python3 is to add these two lines before the merge:

    deu['stName'] = deu['stName'].astype(str)
    deu['stName'] = [st[2:-1] for st in deu.stName.values]

I don't think the python2 version will work with this though...

**Comment by DanielAndreasen** [comment]
Can you try now with the latest commit? If it works, then you can close this issue.
It works here.

**Comment by jason-neal** [comment]
Yes that's got it working!
