### ISSUE TITLE
Missing columns in table header

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#100]
First of all. Congratulation to us with issue/PR #100! Let's celebrate with an extra long Christmas holiday.

In the new and much faster version of the table, not all the columns are shown in the header of the table. All data in the table can be shown by using the scrollbar in the bottom, but this does not affect the header of the table.

**Comment by jason-neal** [comment]
So should the header bar should scroll in line with the columns?
I am seeing weird things in which the header line changes the columns it shows when scrolling up and down.
(I think because the size of the data visible is changes, which changes column size dynamically.)

**Comment by DanielAndreasen** [comment]
That is true, I also see that. But if the horizontal slider is all the way to the left, the columns seems to match. However, I am never able to see the most right header names, just the data when I scroll horizontally to the right.
