### ISSUE TITLE
Double authors.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#101]
Is there a way to handle multiple authors/papers?

Currently the couple of papers with double authors only link to one of the papers. I assume there should there be separate links for each.

On a side note the link for  `Villaver et al. 2017, Zielinski et al. 2012` ( BD+03 2562)  doesn't seem to be valid.

There also seems to be a less stars with double author than I remember, but that could just be me.

**Comment by DanielAndreasen** [comment]
This should be solved now
