### ISSUE TITLE
Incorrect star example in test_stardetail_no_planets

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#106]
https://github.com/DanielAndreasen/SWEETer-Cat/blob/fe134b21b416848add1f292f30e1840a7e3dbb11/sweetercat/tests/test_app.py#L266

I think this is an incorrect example. `GJ 667C` has many planets all will sma, So does not match the test name, doc string or comments. 

Also the name is incorrect compared to database it should be `GJ 667 C`.

**Comment by DanielAndreasen** [comment]
Alright, let's find another one :) Maybe it has been updated, or I did a mistake.

**Comment by jason-neal** [comment]
@DanielAndreasen  By definition shouldn't all stars in SWEETCat have a planet? 
Hence I don't think ´test_stardetail_no_planets`  is correct/possible.

**Comment by DanielAndreasen** [comment]
You are right. They should all have a planet. I can honestly not remember what we wanted to test here.

**Comment by jason-neal** [comment]
Neither can I. The handy commit message says. 
"Test stardetail when exoplanetEU and SC does not connect".

From this I take it that if there is a planet in SC but no planet given by exoplanetEU?
On the DataFrame join of SC and exoplanetEU I assume (cant remember) the missing columns will get filled in with nans/blank.

Therefore to test this we would somehow need to set the planet parameters to nans. 
Although I am not sure how change this for this test only.

With this the test case star is still incorrect. Are you ok if I just delete this test?

**Comment by DanielAndreasen** [comment]
I think it comes from how we combine the two data sets. Feel free to delete it. I close this issue then.
