### ISSUE TITLE
Python 3 only?

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#108]
- The latest version of Astropy (3.0) is Python 3 only, with no python2 support after 2019.
- Numpy will also drop python2 support in 2019 .
- And then no Python2 support past 2020 [https://pythonclock.org/]

So we should therefore aim to get SWEETer-Cat running as python3 when put at CAUP.

**Comment by jason-neal** [comment]
For now we can pin Astropy to < 3 https://github.com/pyupio/pyup/issues/263

     `Astropy==2.0.4  # pyup: < 3 until 2019-12-31`

This will need to be extended in the when numpy and others switch. (if we want to stay current.

**Comment by DanielAndreasen** [comment]
Hi Jason,
I think it's fine if we move to python3 only. Let's follow the rest of the community.
