### ISSUE TITLE
plot - automatic scaling

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#11]
It would be nice to ignore the axis ranges sometimes.

Possibly with separate toggles for x and y separately. 
Possibly have it set automatic by default (showing all the values)
Then set a checkbox to enable to ranges set with xmin, xmax, ymin, ymax.

**Comment by DanielAndreasen** [comment]
I'm not sure I understand this. Can you explain it?

**Comment by jason-neal** [comment]
Nevermind it plots all the data to begin with anyway.  (no min/max limits applied, that requires a second submission)

**Comment by DanielAndreasen** [comment]
So we can close it?
