### ISSUE TITLE
Remove stName from exo-plot choice. 

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#12]
stName should probably be removed from plot-exo parameters to plot.

Selecting stName plots most values at 0 so is not very informative but it also changes the min/max values to star names. 

Then if you try to select a different parameter (without changing the limits) you get.
```
builtins.ValueError
ValueError: could not convert string to float: '11 Com'
```

**Comment by jason-neal** [comment]
If it is chosen as the color choice I get.

`
TypeError: unsupported operand type(s) for -: 'unicode' and 'unicode'
`

**Comment by DanielAndreasen** [comment]
Fixed!
