### ISSUE TITLE
Update the CSS. Bootstrap4?

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#132]
Some of the boxes for input (for plots) looks bad. We probably need to switch to bootstrap 4.

![image](https://user-images.githubusercontent.com/4519017/45573889-4c405d00-b86e-11e8-9633-163315749ae9.png)

**Comment by jason-neal** [comment]
How easy is that? 
Is it as simple as changing something like bootstrap=3.xx to bootstrap=4.0 without changing much else?

**Comment by DanielAndreasen** [comment]
I'm not sure. It was getting late when I saw this. It could be more thant that. Here it also seems like it is only the dropdowns that are a problem.

**Comment by jason-neal** [comment]
From https://getbootstrap.com/docs/4.1/getting-started/introduction/
The new link should be 
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">` 

to replace line 11 from `sweetercat/templates/template.html`

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/united/bootstrap.min.css">`

I have not had a chance to test this yet but there should not be any breaking changes.'

I am not sure if there is a difference between `maxcdn` and `stackpath`. 

Also not sure if the other links need to be updated also.
`datatables` and `scroller`

**Comment by DanielAndreasen** [comment]
Note that the one already there is from bootswatch with the theme included. We should probably go there to find the proper new link.

**Comment by jason-neal** [comment]
Ahh thanks,
That would be 
`<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/united/bootstrap.min.css" rel="stylesheet" integrity="sha384-+d4wMJSxEP3vzs2qZBElQRTZMXwgWH15Nyn2K/9XjKiHmh3sBuk1Un/IbcdMcYC4" crossorigin="anonymous">`
