### ISSUE TITLE
Sousa+18 parameter update broke author/links

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#135]
The newest parameters are not deployed yet.

The build fails with 
```
__________________________ test_homepage_status_code ___________________________
client = <FlaskClient <Flask 'app'>>
    def test_homepage_status_code(client):
>       homepage = client.get(url_for("homepage"))
tests/test_app.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
...
app.py:16: in homepage
    df['alink'] = list(map(author_html, df['Author'], df['link']))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
author = nan, link = nan
    def author_html(author, link):
        """
        Create HTML anchor tag for author with correct link to ADSABS
    
        Inputs
        ------
        author : str
          Name of the author(s)
        link : str
          Link to article
    
        Output
        ------
        alink : str
          Author anchor tag to link
        """
>       if (',' in author) and (',' in link):
E       TypeError: argument of type 'float' is not iterable
utils.py:313: TypeError
```
The author and link are both `nan` so the code fails.

Two possible options:
-  We need to add a patch to allow author/links to be missing. Change the NULL to the required null string early. The input types for `author_html() ` are already specified as string so the fix should probably go outside this function so that it does not get given the float `nan`.

OR

- There is an problem with the database itself that needs to be fixed. 
    @acsferreira Are there any authors or links that are supposed to be NULL?

**Comment by DanielAndreasen** [comment]
It seems that the link is not filled (I checked some of the commit diff). I think it is right that the build failed, since we should have a reference for the parameters.

**Comment by jason-neal** [comment]
Ahh good spotting, I also looked some of the diff but couldn't spot the issue.

**Comment by acsferreira** [comment]
I already sent an email to exoplanet.eu to fix the problem of the planets without reference papers. In the case of the updates done by the new paper of Sergio I am just waiting the paper to be submitted in arxiv to update the link.

**Comment by DanielAndreasen** [comment]
Great job :) Then we just wait.

**Comment by DanielAndreasen** [comment]
I forced a deploy to solve #137. So, now the homepage does not work, but subpages like https://sweetercat.herokuapp.com/publications/ are fine. This will be solved, when we have the links.

**Comment by jason-neal** [comment]
I would have thought a working home page would be higher priority than the minorit style change.

**Comment by DanielAndreasen** [comment]
It certainly is, but I forgot about that. And I don't want to make a roll back

**Comment by jason-neal** [comment]
@acsferreira  I think this is the link http://adsabs.harvard.edu/abs/2018arXiv181008108S

**Comment by jason-neal** [comment]
> I think it is right that the build failed, since we should have a reference for the parameters.

I have added some tests to the database to explicitly check that every star has a name `Star`, an `Author` and a `link`.  #138

If an `Author` or `link` are missing the failing tests will print the name of the star missing the link. (That will hopefully make it easier to find/fix them.)

**Comment by acsferreira** [comment]
still waiting for the corrections in exoplanet.eu, some stars are still without reference...

**Comment by DanielAndreasen** [comment]
These stars still miss information after running the test Jason did:

- [ ] - CoRoT-30   
- [ ] - CoRoT-31   
- [ ] - HD 106574  
- [ ] - HD 118904  
- [ ] - HD 164428  
- [ ] - HD 202432  
- [ ] - HD 44385   
- [ ] - HD 97619

**Comment by DanielAndreasen** [comment]
For the two CoRoT stars the author is Borde et al. 2017, but I can't find a paper for that.

**Comment by jason-neal** [comment]
Yes I could also not find it Borde 2017 (even on his own website). 
http://adsabs.harvard.edu/abs/2018AJ....156...64J   is for HD 44385, HD 97619, HD 106574, HD 118904, HD 164428, and HD 202432

**Comment by jason-neal** [comment]
Hey @odemangeon do you know where the paper Borde et al. 2017 on [CoRot 30b](http://exoplanet.eu/catalog/corot-30_b/) and [CoRot 31b](http://exoplanet.eu/catalog/corot-31_b/) is?

**Comment by DanielAndreasen** [comment]
I tried searching for other authors in the "paper", parts of the title, even the stars, and I can't find anything. Maybe we should contact the author? Or exoplanet.eu

**Comment by acsferreira** [comment]
Thanks Jason, I updated the data with the paper you found.

**Comment by jason-neal** [comment]
Hmm with all papers with an author the tests are now only now failing due to the test requiring a paper link. (the Home page is not failing.)
https://travis-ci.org/DanielAndreasen/SWEETer-Cat/jobs/445035196

**Comment by odemangeon** [comment]
Hi Guys, sorry for not being more reactive. I have just seen our messages.
Bordé is now director of the Observatory of Bordeaux in France. Papers take much longer to be published in these conditions. :)
The paper appears as submitted to AJ, so I guess that there is not much to do expect waiting for it to be accepted.

**Comment by jason-neal** [comment]
Thanks @odemangeon (Its ok it was only yesterday). 

@DanielAndreasen @acsferreira A question then is should CoRoT-30 and -31 still be included in SWEET-Cat without the published paper (until it is published)?

**Comment by acsferreira** [comment]
I can remove without problems if you think is easier.

**Comment by DanielAndreasen** [comment]
Not only easier, but also more correct since it is technically not published yet.

**Comment by acsferreira** [comment]
the agreement was if is in exoplanet.eu then should be in Sweet-Cat. I understand these cases are problems and I can remove for now until the paper is out.

**Comment by odemangeon** [comment]
A comment:
In this particular case, Jean Schneider is in CoRoT and he is probably (95% of probability :)) co-author of the paper. So I am pretty sure that the parameters of exoplanet.eu for CoRoT-30 and CoRoT-31 are identical to the one of the submitted paper.
However, I understand that it might be too complicated and/or sound a bit biased to take into account this kind of information. So if it's the case, please ignore the comment. :)

**Comment by DanielAndreasen** [comment]
I am not sure what the final conclusion is here. Should the two stars be
1. Deleted (and probably added again in the future, when the paper is published)?
2. Let them be (and the homepage is broken)?
3. Maybe add a default page (to ADS? or exoplanet.eu?)?

It could be nice with a guideline for the future.

Furthermore, it could be nice if the person who updates (which is mostly @acsferreira) does it through a pull request. I know it is a bit tedious, but it will catch the errors earlier on.

**Comment by sousasag** [comment]
If the planets are listed in exoplanet.eu, they should be listed in Sweet-cat.
If the parameters and not yet published, then put exo.eu parameters if any. if there is no publication link, Leave it as it is, without a link for now.

**Comment by DanielAndreasen** [comment]
If there is no link, the code crashes. In those rare cases I suggest having a link to exoplanet.eu. Do you agree?

**Comment by jason-neal** [comment]
A fourth option is to adapt the code to allow the link to be not present in the database - Either remaining empty or pointing to exoplanet.eu.

**Comment by sousasag** [comment]
I agree, if this avoids the crashing, just put a link to exoplanet.eu.

**Comment by jason-neal** [comment]
Home page is working again with the addition of exoplanet.eu links working for corot-30 and-31 (and any future planets with missing links)
