### ISSUE TITLE
Bokeh plots - Selection tool default should not be blue.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#136]
Currently with the default blue the selection tool "appears" not to work as the default non-selected color is the same as the selected color (selected color can be chosen and is fine when a different color is selected).

I think possibly a greyer color, and/or a decrease in alpha might help.

**Comment by DanielAndreasen** [comment]
Nice spot. I think I prefer just to redefine the default colour. No need to start making sure the colours would never be the same.
