### ISSUE TITLE
Plot - error when x = y = z

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#14]
When x is the same as y or z or any other combination, it doesn't work. Gives following error:

    AttributeError: 'DataFrame' object has no attribute 'name'

Basically we expect a `Series` but get a `DataFrame`

**Comment by jason-neal** [comment]
I can plot x = y = z with fac2b6aa7b (but not  3d2a886)so it might be due to the newer parts you have added.

**Comment by DanielAndreasen** [comment]
The problem is this commit f87e4312361025b9b. But it fix more than it broke.

**Comment by DanielAndreasen** [comment]
Found a simle solution using `list(set(cols))`
