### ISSUE TITLE
Total objects in plotting window?

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#16]
Would it be useful to have a tally of objects displayed on the plot? Which changed depending on the limits

Something like
`num_points = np.sum( x > xmin & x < xmax & y > ymin & y < ymax)`

**Comment by DanielAndreasen** [comment]
Good idea. I guess we can add a label somewhere with this information

**Comment by DanielAndreasen** [comment]
Let's just add this to the title. That makes sense I would say.

    num_points = np.sum( x > xmin & x < xmax & y > ymin & y < ymax)
    title = '{} vs. {}\tNumber of objects in plot: {}'.format(x.name, y.name, num_points)

**Comment by jason-neal** [comment]
I removed your initial titles "HR diagram"/"Towards Earth 2.0" as I moved the title below the flag masking.

If you want we could put another if/else around the title element.

**Comment by DanielAndreasen** [comment]
I think that is fine. It's not super important
