### ISSUE TITLE
Depreciation warning

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#17]
This might be just a python3 thing but I get this warning when including the z parameter. [Disscussion of issue here]( https://github.com/bokeh/bokeh/issues/2056 )

```
BokehDeprecationWarning: 
Supplying a user-defined data source AND iterable values to glyph methods is deprecate
```

I think we might need to add the color to the ColumnDataSource. 

This is only a warning so is not urgent.

**Comment by DanielAndreasen** [comment]
I get the same warning in python2. I would like to solve it though

**Comment by DanielAndreasen** [comment]
It was a simple fix, and `ColumnDataSource` was, well, the source of the problem. It's fixed now.
