### ISSUE TITLE
Rendering main page with full database is slow

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#19]
Title says it all. It's incredible slow to render the full table. We need to implement something like [this](https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html).

**Comment by jason-neal** [comment]
When I load the page , all the entries (50 atm) show up and then it gets cut to the 10 entries.

**Comment by DanielAndreasen** [comment]
Exactly. I don't know a simple solution to solve this other than try to implement the solution from the link above. But it looks tricky.

**Comment by jason-neal** [comment]
Did you use [this](https://datatables.net/download/)?
The last option is to host locally, I am not sure if this is what you have done already.

**Comment by DanielAndreasen** [comment]
I never answered your question, sorry about that.
No, I did not use that. Basically the "import" of datatables is done with CDN and not from a local file (see L10 in template.html). Maybe having a local copy with the link you send is another way to go about it.

I also found this tool that might be interesting: https://github.com/vividvilla/csvtotable

**Comment by DanielAndreasen** [comment]
This seems to be fixed finally with commit e0d07e5593316922bdce
