### ISSUE TITLE
Separate file for non flask code.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#23]
The plotting code is getting large.

Eventually, we move all non-flask code into a separate file/module. e.g. the plotting code and other functions.

This would keep app.py smaller and tidier.

To be done in the future sometime.

**Comment by DanielAndreasen** [comment]
This is being done on branch [tidy-up](https://github.com/DanielAndreasen/SWEETer-Cat/tree/tidy-up) with commit e201eb83c042ab28f99fa8e
