### ISSUE TITLE
Planet density

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#27]
Since we have the planetary mass and radius, we should also provide the planetary density for the plots.

**Comment by jason-neal** [comment]
Sounds good, I wonder if there are any other interesting parameters we can determine from current parameters.

I guess it would is outside the current scope to include the composition lines when plotting mass/radius, 100% water, 100% iron etc.

**Comment by DanielAndreasen** [comment]
Sounds out of scope for SWEET-Cat in my opinion. This should probably be done by the researchers.
We could provide an estimate of habitable zone (HZ) limits.

**Comment by jason-neal** [comment]
Added planet density to tidy-up branch, 977bda8cfa

**Comment by DanielAndreasen** [comment]
What's the volume of a sphere? :)

**Comment by jason-neal** [comment]
As big as it wants to be. (It's late)

**Comment by jason-neal** [comment]
Planet density was included in the merge into main with  58c79ff.
Up to you if you want to close this and make a separate "Other parameters" issue for things such as HZ limits, or keep this open.
