### ISSUE TITLE
Cosmetic - Stop line wrapping?

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#3]
When I first opened the page my first thought was the large spacing between the entries.
![database](https://user-images.githubusercontent.com/10076879/27905160-03d02962-6237-11e7-862e-fd31ceae2c0f.png)

This is caused by the line wrapping of RA, Dec, and the author columns. 

This is a cosmetic issue but maybe we need to turn off the line wrapping.

**Comment by DanielAndreasen** [comment]
I agree. Not sure at the moment how to solve this. But Google might help us here. Maybe specify a width of the columns.

**Comment by DanielAndreasen** [comment]
I can see you are working on this now. The table use bootstrap. Maybe you should look into this

**Comment by jason-neal** [comment]
From some searching, `white-space: nowrap`  in the CSS should stop the line wrap.
