### ISSUE TITLE
Comprehension lists instead of map?

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#32]
Comprehension lists are considered more "pythonic" and I find them easier to read.

What do you think?

**Comment by DanielAndreasen** [comment]
I'm just in a phase where I really like map and and lambda expressions. But I don't have a strong argument for either. You can change them if you prefer

**Comment by jason-neal** [comment]
In python2 when the `list()` is not required then `map` is of similar line length. I have changed them.
