### ISSUE TITLE
Pandas Setting with Copy warning.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#33]
Warnings when modifying the data frame. This is one example of the warning message.
```
app.py:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: [here](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy)
  d['plName'] = [s.decode() if isinstance(s, bytes) else s for s in d['plName']]
```
So maybe there is a "better" way to do this.

**Comment by DanielAndreasen** [comment]
Yes, I also wanted to open an issue on this, because I see it quite often now. And it's really annoying. I will have a look at some point. It clutters the log.

**Comment by DanielAndreasen** [comment]
Has been solved with commit above.
