### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#40]
I am looking into some adding some automated testing.
To help with finding bugs and the  py2 and py3 compatibility.

The basics to start with would be.
 - [x] Open each main page and check that it returns 200.
 - [x] Open some random `stardetail` pages (w or w/o planet details) 
 - [x] POST requests to the plot/plot-exo pages (random parameter combinations)?
 - [x] Link to Travis, to build on PR and commits.  (py2 and py3 builds)

 - [x] Is it possible to inspect the reusult of `render_template(`)?
#### Some useful links:
- [pytest-flask](https://pytest-flask.readthedocs.io/en/latest/)
- [flask testing ](http://flask.pocoo.org/docs/0.12/testing)/
- [pytest examples](https://docs.pytest.org/en/latest/example/index.html)
- [hypothesis](https://hypothesis.readthedocs.io/en/latest/l) for the random target/parameter sampling?

**Comment by DanielAndreasen** [comment]
I agree on this! We have reached a critical point where testing is necessary. Our PRs start to break functionalities.

**Comment by jason-neal** [comment]
Exactly!

**Comment by DanielAndreasen** [comment]
Indeed, I think we should prioritise this over some of the other issues and PRs at the moment. It will speed up our process in the long run.

**Comment by jason-neal** [comment]
This has been implemented in #41 and #42.

**Comment by jason-neal** [comment]
Closing as we have started to get some good testing practices going and seems to be working well.
