### ISSUE TITLE
Is there an intended purpose for the login button on top of the homepage?

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#46]
If not then should it be removed from the template?

**Comment by DanielAndreasen** [comment]
Not sure about it. The initial idea is/was to have an interface for editing/adding new stars. Let's keep it for now, it's just one line of code that can easily be removed if we don't find a use for it.

**Comment by DanielAndreasen** [comment]
I removed the login button for now.
