### ISSUE TITLE
Default plot form values

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#49]
It would be nice for testing if we didn't have to set and pass in all the plot form values  (`test_data` here) each time.
```
test_data = {"color": "Blue", "x": "teff", "y": "mass", "z": "None",
                 "x1": 8000, "x2": 2500, "y1": 0, "y2": 5,
                 "xscale": "linear", "yscale": "log", "checkboxes": ""}
plot = client.post(url_for("plot"), data=test_data, follow_redirects=True)
```
But just the one or two values you want to test at the time such as `test_data = {"x": "feh",, "xscale":"log"}`

e.g. We could give default values if key is not in` request.form` by changing
 `color = request.form['color']`  -> `color = request.form.get('color', 'Blue')`

One possible problem with this is if the template is changed and broken (so that the form is missing values) then the app will still "work" without raising an error).

**Comment by DanielAndreasen** [comment]
I kind of like this idea to get a default value if non is selected. For the testing I guess you could also just define the full `test_data` outside any functions in the top of the file, and then just adjust it in the individual testings. Is that a possibility?

**Comment by jason-neal** [comment]
Ahh yes that is a possibility,  a `test_data` fixture.

**Comment by jason-neal** [comment]
A `default_form` test fixture was added and used in 394ceb64c7
