### ISSUE TITLE
Tidying up plot code

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#50]
I have created a `tidy_plot_code` branch to tidy up the plot code, and to test individual pieces.

I have taken out the histogram creating and scaling, so far to reduce the duplication in the main function.
I was trying to do the whole histogram section but it was getting complicated.

```
def add_historgram(fig, data, axis="x", scale="linear"):

     num_points = len(data)

     if scale == 'linear':
         hist, edges = np.histogram(data, bins=max([5, int(num_points/50)]))
     else:
         h1, h2 = np.log10(min(data)), np.log10(max(data))
         hist, edges = np.histogram(data, bins=np.logspace(h1, h2, max([5, int(num_points/50)])))
     hist_max = max(hist) * 1.1

     if axis == "x":
         w, h = fig.plot_width, 200
         x_range, y_range = fig.x_range, (-hist_max * 0.1, hist_max)
         x_axis_type, y_axis_type = scale, "linear"
     elif axis == "y":
         w, h = 200, fig.plot_height
         x_range, y_range = (-hist_max * 0.1, hist_max), fig.y_range
         x_axis_type, y_axis_type = "linear", scale

     phist = figure(toolbar_location=None, plot_width=w, plot_height=h, x_range=x_range,
                    y_range=y_range, min_border=10, min_border_left=50, y_axis_location="right",
                    x_axis_type=x_axis_type, y_axis_type=y_axis_type)

     if axis == "x":
         phist.xgrid.grid_line_color = None
         phist.yaxis.major_label_orientation = np.pi / 4
     else:
         phist.ygrid.grid_line_color = None
         phist.xaxis.major_label_orientation = np.pi / 4
     phist.background_fill_color = "#fafafa"
  # Deal with edge sizes.  
  # pv.quad(left=0, bottom=vedges[:-1], top=vedges[1:], right=vhist, color="white", line_color=colors[color])

     return phist

```

Then in the `plot_page` we would just need to write
```
ph = add_historgram(fig, data, axis="x", scale="linear")
pv = add_historgram(fig, data, axis="y", scale="linear")
```

What do you think?

**Comment by jason-neal** [comment]
This code here could also be reduced/simplified. Especially since it sets them then possibly overwrites them if the session is not correct.
```
# Setting the limits
        limits = [request.form['x1'], request.form['x2'],
                  request.form['y1'], request.form['y2']]
        for i, lim in enumerate(limits):
            try:
                limits[i] = float(lim)
            except ValueError:
                if i == 0:
                    limits[i] = min(x)
                elif i == 1:
                    limits[i] = max(x)
                elif i == 2:
                    limits[i] = min(y)
                elif i == 3:
                    limits[i] = max(y)
        x1, x2, y1, y2 = limits

        if x.name != session.get('x', None):
            x1 = min(x)
            x2 = max(x)
            session['x'] = x.name
        if y.name != session.get('y', None):
            y1 = min(y)
            y2 = max(y)
            session['y'] = y.name
```

**Comment by DanielAndreasen** [comment]
I think it's a good idea to move some of these simple/duplicated/tedious things to small functions like this. I did make a function myself for setting the limits, but it hasn't been commited yet (not sure how to test it).

```
def set_limits(request, x, y):
    limits = [request.form['x1'], request.form['x2'],
              request.form['y1'], request.form['y2']]
    for i, lim in enumerate(limits):
        try:
            limits[i] = float(lim)
        except ValueError:
            if i == 0:
                limits[i] = min(x)
            elif i == 1:
                limits[i] = max(x)
            elif i == 2:
                limits[i] = min(y)
            elif i == 3:
                limits[i] = max(y)
    return limits
```
I would also like to have it written more elegantly, but not sure how to do this.

**Comment by jason-neal** [comment]
What about a function that does similar to give a default value if `key` not in `dict` 
*Not sure what best to call the variables though*
```
def default_float(x, default): 
    try:
       return float(x)
    except ValueError:
        return default
```
then
```
limits = [request.form['x1'], request.form['x2'],
             request.form['y1'], request.form['y2']]
defaults = [min(x), max(x), 
                 min(y), max(y)]
for i, lim, default in enumerate(zip(limits, defaults)):
     limits[i] = default_float(lim, default)
```

or more generally pass in the float fuction aswell,
def default_on_fail(func, x, default):
    """return default if func(x) returns error"""
    pass

**Comment by jason-neal** [comment]
To test limits function, maybe somthing like...
```
def test_set_limits():
    x = range(5)
    y = range(5,10)
    request_form = {"x1": 1, "x2: "two", "y1" : "", "y2": [4]}
    limits = set_limits(request_form , x, y)
    assert  == [1., 4., 5., 9.]
    for lim in limits:
        assert  isinstance(lim, float)
```

This will probably fail since x and y are `int` at the moment, so may need to wrap the defualt value in `float()` as well.

**Comment by DanielAndreasen** [comment]
Good ideas. I will look into this eventually.

**Comment by DanielAndreasen** [comment]
Function and test added in commit 8aa40e4521dbcf. However, I'm not sure how to deal with the `request.form` part, so added a check in [L219-L222](https://github.com/DanielAndreasen/SWEETer-Cat/blob/8aa40e4521dbcf8b8559a47900281026b2ad7e47/sweetercat/plot.py#L219-L222). It was the easiest quickfix to make the test pass

**Comment by jason-neal** [comment]
Could you not just pass `set_limits(request.form, x, y)`? 
You wouldn't need to call the variable `request` either.

**Comment by jason-neal** [comment]
I moved the counting the number of points into a separate, to make the main code nicer.

**Comment by DanielAndreasen** [comment]
Very nice! I think we should shuffle/randomly draw stars from the DB when we use just 5 or 50, like in a place like [this](https://github.com/DanielAndreasen/SWEETer-Cat/blob/clean_plot_code/sweetercat/tests/test_app.py#L33). I'm sure `Pandas` have ways to do this.

**Comment by jason-neal** [comment]
```
DataFrame.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)

    Returns a random sample of items from an axis of object.
```

**Comment by jason-neal** [comment]
Although this has the problem that we may not know what the "failing" star is if it fails. So may need to include a `print(stars) ` in the test (it only prints out if the test failed)

**Comment by DanielAndreasen** [comment]
Does it not show the traceback during failure? Otherwise we add a `print(stars)` and a `-s` to the `pytest` command.

**Comment by jason-neal** [comment]
No I don't believe so. 
It usually just prints out the assert line that fails, something like...
```
Failed test ....
def fake_test():
> assert x == y

 where x = ...... 
 and y = .... 
```
If you are in a loop it doesn't tell you what value the iterable is currently at. (as far as I am aware).

**Comment by DanielAndreasen** [comment]
But is usually also prints the value of `x` and `y`. But alright, don't know if it is different in a loop. In any case, we should only print something if there is an error:
```
try:
    assert x == y
except Exception:
    print(x, y)
    raise Exception
```

**Comment by jason-neal** [comment]
From what I have seen, by default, pytest does not print anything if the test passes. But it will print out any statements you try print if the test fails. (I do this for exploration when debugging failing tests sometimes) 

Yes it does print out the values of `x` and `y`, but that would not be helpful if we were choosing random stars to test. 

An example straight from our code then is (assuming `stars` is a fixture with  the star names)
```
def test_stardetail_status_code(client):
    """Test stardetail will return status code: 200 when submitted with star"""
    df, _ = readSC(nrows=5)
    # All stars are a slow test
    stars = df.Star.values
    for star in stars:
        assert client.get(url_for("stardetail", star=star)).status_code == 200
```
If this test fails pytest will tell us that `client.get(url_for("stardetail", star=star)).status_code = (not 200)` and 200 = 200,
but I am pretty sure it will not tell us the value of `star` or `stars` in the traceback.

I am also not sure that the try-except code will work in the tests. Pytest takes the assert code and does funky things with it (from what I recall from podcasts I've listened too).

**Comment by DanielAndreasen** [comment]
Okay, you are the expert :) As long as we can see which `star` might give an error, I will not complain.

**Comment by jason-neal** [comment]
I have added the sampling in 28f3c9737d6b, 
Had to use `stars.iteritems() `instead  of `enumerate(stars.values)` to get the correct index values.

I also added` print(star)` in the iterations.

**Comment by jason-neal** [comment]
PR #52 has been merged into master now.
