### ISSUE TITLE
Particle with horizontal scrolling on homepage.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#55]
The table on the homepage is wide. When scrolling to see the right edge the particle box is cut off :( 
It is also in line with the search box included in the picture below.

I don't know if this is easy to change or not..
Would we need to include a horizontal scroll embedded into the table to explore the data so the whole page doesn't need to move?

![screenshot from 2017-08-08 23-31-24](https://user-images.githubusercontent.com/10076879/29097552-67395224-7c92-11e7-8630-c1dd568cf171.png)

**Comment by DanielAndreasen** [comment]
1) This was also the case before as far as I know. The navbar would not cover the entire width.
2) As the table is (maybe) not in it's final stage (issue #19), the horizontal scrolling might change in the future.

**Comment by DanielAndreasen** [comment]
This has been resolved at some point.
