### ISSUE TITLE
Change from Bokeh to mpld3

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#59]
It is worth considering changing to [`mpld3`](http://mpld3.github.io/), which basically takes `matplotlib` `fig` element and render it as HTML. It comes with all the known functionality of `matplotlib`.

**Comment by DanielAndreasen** [comment]
An exmaple of it in use can be seen at the [mpld3](https://github.com/DanielAndreasen/SWEETer-Cat/tree/mpld3) branch. Here some of the functionality is recreated, but with four plots.
Highlight some part to see mpld3 in action. Zoom and drag are also more interactive.

**Comment by jason-neal** [comment]
That's really neat! We never managed to get the highlighting for bokeh to work.

**Comment by DanielAndreasen** [comment]
I think a mix of mpld3 and bokeh works fine. I will close this issue
