### ISSUE TITLE
Mutliple planets all labeled _b 

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#63]
All planets in a multiplanet system are labeled `_b` 

e.g. `GJ 876` and `GJ 849`.

**Comment by DanielAndreasen** [comment]
That's unfortunate. I will have a look at that.

**Comment by DanielAndreasen** [comment]
And it's solved.

**Comment by jason-neal** [comment]
I added a note to the commit of how to `cherry-pick` this bug fix into `master` branch.
