### ISSUE TITLE
Make request async

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#64]
When the exoplanet database is being downloaded, it blocks for other pages to be open. E.g. when starting up the server and go to a stardetail page (to tricker the download of exoplanet database), then open in another tab the publications list (which is very fast). The publication page will only open once the database is fully downloaded.
I think it is possible to use `async` to solve this, but I have never tried it.

**Comment by jason-neal** [comment]
Here are a couple of options/examples I quickly found [flask-aiohttp](https://flask-aiohttp.readthedocs.io/en/latest/), [async_flask.py](https://gist.github.com/viksit/b6733fe1afdf5bb84a40)
[Here](https://pawelmhm.github.io/asyncio/python/aiohttp/2016/04/22/asyncio-aiohttp.html) is also a blog post on asyncio-aiohttp.

The problem you are noticing though is a an issue with the flask default sever,
From the Flask [deployment options](http://flask.pocoo.org/docs/0.12/deploying/)

> Flask’s built-in server is **not suitable for production** as it doesn’t scale well and by default serves only **one request at a time**.

You are seeing the one request at a time when publications is waiting for the database to download.

We need to figure what to use to deploy `SWEETer-CAT`. Maybe the IT department have specifications on what is recommended/allowed? 

I am not su

**Comment by DanielAndreasen** [comment]
I just remembered [`gunicorn`](http://gunicorn.org/) which is a much easier solution to this problem. Try install it with `pip install gunicorn` and run `gunicorn -w 4 app:app` in the `SWEETer-Cat/sweetercat` directory. This will start four workers, and solves the issue.
By default it opens on port 8000 instead of 5000. This can be changed by specifying the `--bind/-b` flag: `gunicorn -w 4 -b 127.0.0.1:5000 app:app`

The argument `app:app`: here the first is the filename, and the latter is the application name (`app = Flask(__name__)`)

**Comment by DanielAndreasen** [comment]
With the configuration file introduced in commit 19744d8d23dda0e, just run the command as `gunicorn -c config.py app:app` and all should work. See options for the configuration file [here](http://docs.gunicorn.org/en/stable/settings.html).
