### ISSUE TITLE
SC publications

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#65]
We need more SC publications. Some can be found [here](https://ui.adsabs.harvard.edu/#search/q=full%3A%22SWEET-CAT%20%22&sort=citation_count%20desc%2C%20bibcode%20desc). Just be careful to only use those which directly use the results from SC, and don't just mention the catalogue. So a quick read will be necessary.

**Comment by jason-neal** [comment]
I have started compiling a list of papers that use SWEET-CAT parameters from the link above.

Would papers that contribute parameters to sweet-cat go under main papers? e.g. [Mortier 2014](https://ui.adsabs.harvard.edu/#abs/2013A&A...558A.106M/abstract), and [Tsantaki 2014](https://ui.adsabs.harvard.edu/#abs/2014A&A...570A..80T/abstract)

**Comment by DanielAndreasen** [comment]
I would say yes. But I have no strong feelings about it. The paper by Mortier+ 2014 does more than adding parameters, so in principle it could go both places. Then I think it makes most sense to only add it for the main.

**Comment by jason-neal** [comment]
I have added the new publications in PR#68 from the list above.

 `test_publication_response_data()` fails now in [build #155](https://travis-ci.org/DanielAndreasen/SWEETer-Cat/jobs/279063034) with the addition of new publications. 

The quote mark character `'` is transformed into `&#39;`  in the html. When the abstract test is checking the abstract content in the html this fails as the sentence is different in the html. 

The test passes for all abstracted if the section of text checked it reduced from 480 characters to 100, but I am not sure on that "fix", Maybe we could check for `'` in the abstract first and convert to `&#39;`. I am not sure if either of these is the best solution though.

**Comment by DanielAndreasen** [comment]
Great job. I changed the HTML slightly and removed the `escape` call in the test. In the HTML file I added `|safe`.
Obviously this issue is always relevant, but I think you have done a great effort to mark it as closed now.
