### ISSUE TITLE
Download exoplanet.eu VO table

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#67]
Since the download of exoplanet.eu is really slow, then it might be worth having a copy of it locally (and here on github), and just upload it once per week.
This can potentially solve many of our performance problems. The only disadvantage is that the table might be outdated by up to 7 days, which isn't bad at all.

**Comment by jason-neal** [comment]
The 7 days outdated is fine. 
Once it is running on the server then the inital startup time would would be a one time thing?
How would the cache handle the db being updated? probably would need to force an update of the cached value after updating the db.

If we continued with exoplanet.eu I am not sure that it would automatically update itself either. (as we would only access the cached versions?) I am not sure about this but. 

So probably either way would need some schedualed update thing (weather its call exoplaneEU like we do in the initalization or a manual download/update)

**Comment by DanielAndreasen** [comment]
The way I envision it, that we "manually" download the VO table once per week and have it stored in this project. Additionally we will have our own reader (bypassing PyAstronomy) for the table. This will then be pushed online. This can be done in a cronjob on Linux easily.

Don't confuse it with cache. This is just for a single user. The cache will only be active for 5min. However, having the DB stored should increase the speed overall
