### ISSUE TITLE
plRadius/plMass error

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#8]
When plotting planetary radius against mass, we get the following error:

`ValueError: Out of range float values are not JSON compliant: nan`

**Comment by jason-neal** [comment]
The issue arises from `plRadius`.  

I can plot plMass against other parameters, but not plRadius.

**Comment by jason-neal** [comment]
Also with many other exoplanet.eu parameters, e.g. the band magnitudes.
