### ISSUE TITLE
Plot - homogeneous

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#9]
There should be a button to only include points in the plot, where the stellar parameters have been derived by us.

**Comment by jason-neal** [comment]
Apply a mask using the "Homogeneity flag"?

**Comment by DanielAndreasen** [comment]
Yes, someone just have to code it. It should be an option

**Comment by jason-neal** [comment]
I have added a solution in branch "flag". Adds a checkbox.

Checkbox values are stored as a list.
To simply add extra checkboxes copy the checkbox template line leaving the name as `name="checkboxes"` but change the "value".
You can then test if the "value" is in the `checkboxes` list in app.py

To easily see the difference of the homogeneous flag there are many non-homogeneous values at `vt = 2.0`.

**Comment by DanielAndreasen** [comment]
I think this is safe to merge. Just tested it, and works fine

**Comment by jason-neal** [comment]
Merged in 82de3a7c3
