### ISSUE TITLE
About/contact page

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#95]
We need a page with clear instructions on how to get in contact with us. Could be nice with a generic SWEET-Cat email.

**Comment by DanielAndreasen** [comment]
Do we need anything else than what is visible at https://sweetercat.herokuapp.com/about/?

**Comment by jason-neal** [comment]
Do we need an IA mention/logo/link?

**Comment by DanielAndreasen** [comment]
Don't know. Do you know @sousasag?
