### ISSUE TITLE
Creating database/table images (every 6 months)

### ISSUE THREAD

**Issue by sousasag** [DanielAndreasen/SWEETer-Cat#97]
Every 6 months, or/and, when a big update is performed in sweet-cat, it would be nice to store the database, both sweet-cat and exo.eu tables in an easy to read format (e.g. csv).

This would be nice to be available in a folder like webpage with the list of files containing the data.

Why can this be useful?:
-  Check the evolution of parameters (star and planet[s]) for a given system
-  Check evolution of correlations between planets and host stars (e.g. metallicity correlation of Neptunes)
- Easy way to collect data to compare previous literature values in sweet-cat against new (already updated) homogeneous parameters.
- Keep track of sweet-cat stats (e.g. percentage of homogeneous planet-hosts with time)

**Comment by DanielAndreasen** [comment]
One question: Is this something you want exposed to the public or just for internal use?
As for the format, the data is already in a "easy to read format" which means we have functions that can read it and combine it. Check out the new [local](http://sweetercat.herokuapp.com/local/) site.

**Comment by jason-neal** [comment]
I wonder if a separate archive-like repo was an option with an automated script that downloads the new tables  and then "tags" the repo with the date (for example) and then does a "[release](https://developer.github.com/v3/repos/releases/#create-a-release)".
These "releases" could then be searched/downloaded.

Just a thought I had...

**Comment by DanielAndreasen** [comment]
I like that idea. Just not sure github will like that we have a repo with data that keeps growing like that. The two databases are almost 2MB at the momemt, so probably isn't a real problem.

**Comment by DanielAndreasen** [comment]
@sousasag what do you think about @jason-neal idea?

**Comment by jason-neal** [comment]
I notice @acsferreira did a big change to the database with  a3d731f2f3631e9bdcfa30377c1f0c5058ec2e44 so I have started something here at [parchive](https://github.com/jason-neal/parchive). I have made separate copies of the datafiles with the data added to name. Currently just copied the data from the history of SWEETer-cat back to August 2017.

Checkout a repo at a certain date using. 
`git checkout git rev-list -n 1 --before="2009-07-27 13:37" master`

**Comment by DanielAndreasen** [comment]
If @sousasag is satisfied with this solution we can close this issue.

**Comment by acsferreira** [comment]
I recomputed all the masses that were different from the Torres calibration that is why there are many changes. There is nothing to do with adding new planets in this case so don't need to keep the exo.eu table.

**Comment by DanielAndreasen** [comment]
This is solved
