### ISSUE TITLE
Fix randomly failling stardetail tests.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#99]
There are two test that fail randomly as the stars that are sampled changes each time.
I do not fully understand why these fail but it we need to figure it out.

Having randomly failing tests is **bad testing practice** because it adds confusion and fails the build when the actual change made is not the problem.

The two tests in [`test_app.py`](https://github.com/DanielAndreasen/SWEETer-Cat/blob/master/sweetercat/tests/test_app.py) are.
- `test_stardetail_template_text()`
- `test_stardetail_status_code()`

#### Possible Solutions:
- Split out the test into stars that are know to be fine and an xfail(strict=True) list of stars that it has failed on. This will help identify if it is a star issue or just randomly failing on any star. the strict = True raises an error if a xfail() marked test suddenly starts passing.

- xfail the tests as they are and continue ignoring the problem.

**Comment by jason-neal** [comment]
This may partially be fixed by 217c533.  The `c` parameter of scatter plots was not a sequence.

**Comment by DanielAndreasen** [comment]
No fails since then (related to this) I think.
